### ISSUE TITLE
Doesn't work out of the box

### ISSUE THREAD

**Issue by constantm** [bessey/vscode-rufo#11]
VSCode 1.27.1
rufo extension 0.1.0

I installed the extension, reloaded VSCode and auto-format doesn't seem to work. When manually trying to run it with Format Document, VSCode says
>There is no document formatter for 'erb'-files installed.

**Comment by bessey** [comment]
ERB files are unsupported by Rufo itself at the moment. Only Ruby files (.rb) are supported.
