### ISSUE TITLE
Chinese charactor break vscode-rufo (Error: the given text is not a valid ruby program (it has syntax errors)

### ISSUE THREAD

**Issue by 1c7** [bessey/vscode-rufo#12]
#### Error:Show error when Chinese chatactor inside render json
![image](https://user-images.githubusercontent.com/1804755/49263753-c43e1c80-f486-11e8-8e1b-d219ec468e8e.png)
```ruby
class Api::V1::TestController < Api::V1::ApplicationController
  def show
      render json: { status: 2, message: "不存在" }
  end
end

```
#### OK: without that line, it work fine
![image](https://user-images.githubusercontent.com/1804755/49263782-d324cf00-f486-11e8-956d-2d88b7d12a5b.png)

**Comment by 1c7** [comment]
First of all, thank for for building this plugin,
I am just reporting a bug here, not request anything

not sure if it's `vscode-rufo`'s problem or `rufo` problem
I don't have time to test which one.

if you don't have time to fix it.
Can you post couple links here? 
help me learn about how to fix it myself. and then I can post a  PR here

Thank you very much

**Comment by 1c7** [comment]
```ruby
class Api::V1::TestController < Api::V1::ApplicationController
  def show
      render json: { status: 2, message: "不存在" }
  end
end

```

**Comment by bessey** [comment]
Sorry I haven't been actively maintaining this as I'm not really using it
at the moment.

The plugin is incredibly simple though, if you check the source there's
barely a hundred lines. I bet it's not a hard fix, not that I know much
about character encoding in node...

**Comment by bessey** [comment]
And if you do make a pr I'm happy to review and merge

**Comment by 1c7** [comment]
@bessey understood. Thanks for reply! If I got time for this I may fix it myself and send PR.
