### ISSUE TITLE
Does not format gemfile?

### ISSUE THREAD

**Issue by breathe** [bessey/vscode-rufo#14]
rufo from the command line can format Gemfile's -- but I can't vscode-rufo to ...

even with a section like this ...?
```
 "[gemfile]": {
      "editor.formatOnSave": true,
      "editor.defaultFormatter": "jnbt.vscode-rufo",
      "editor.formatOnSaveTimeout": 3000
    },
```

**Comment by bessey** [comment]
Hmm, I am not `jnbt.vscode-rufo`, thats this guy https://github.com/jnbt/vscode-rufo I am `bessey.vscode-rufo` I think?
