### ISSUE TITLE
Support for Gemfile and ERB formatting

### ISSUE THREAD

**Issue by gingermusketeer** [bessey/vscode-rufo#15]
Rufo now supports formatting of Gemfiles and ERB files so it would be great if this extension did as well.

It looks like the language code is `gemfile` and `erb`. At least this is what is used for customising configuration.

**Comment by bessey** [comment]
I whipped up https://github.com/bessey/vscode-rufo/pull/16 but I am not using Rufo at the moment. Could you verify that it actually works? 😅

**Comment by gingermusketeer** [comment]
@bessey I have tried to test it but don't seem to be able to get the extension to install. Do you have any tips for how I can test this?

**Comment by bessey** [comment]
You need to go to your `~/.vscode/extensions` and replace the extension's directory with a symlink to this git repo.

I've just done it and it doesn't appear to work, not sure why yet

**Comment by bessey** [comment]
Nevermind, got it working, merging shortly

**Comment by bessey** [comment]
Ok, I initially merged and tested with Gemfile which worked beautifully, but ERB broke because I was not using the `--filename` option. That's also added now, and the new version is published with updated changelog and README. Let me know if you have any problems.

**Comment by gingermusketeer** [comment]
Many thanks I will test it out!

**Comment by gingermusketeer** [comment]
@bessey I am getting a syntax error with the latest version when trying to format `.erb` files.  It seems to be treating it as ruby rather than erb. I don't see the `--filename` option that you mention above in the code. Maybe that is the issue?

Gemfiles are working great! 

<img width="798" alt="Screen Shot 2020-01-19 at 12 25 07 PM" src="https://user-images.githubusercontent.com/1177034/72680144-c01ff480-3ab6-11ea-9724-beb2b65d90ae.png">

**Comment by bessey** [comment]
Hey Max, I forgot to push, but i believe I released it with the correct
code, are you using the symlinked version from GH?

Either way, I've re-published after having pushed to be sure.

Matt

**Comment by gingermusketeer** [comment]
I cleaned out the old extensions and restarted vscode seems to have done the trick. Thanks!
