### ISSUE TITLE
How and Where to run Ruby code.  Simple instructions for beginners.

### ISSUE THREAD

**Issue by allstonc** [bessey/vscode-rufo#20]
I've downloaded GitHub, and then Atom.  All I need to do is to see if my code runs successfully in Ruby.  Can someone give me a quick step-by-step way to access the site where I can run code?

**Comment by bessey** [comment]
Sorry, I don't totally understand the question but in any case, this is a repository for a Visual Studio Code extension, not a place for general Ruby support.
