### ISSUE TITLE
/bin/sh: rufo: command not found

### ISSUE THREAD

**Issue by gtournie** [bessey/vscode-rufo#4]
after installed in vscode.

vscode version: 1.20.1

**Comment by gangwang2** [comment]
`rufo` is an external command that needs to be installed with the ruby gem tool.

```
gem install rufo
```

**Comment by edbond** [comment]
Constantly gets "rufo: command not found" error.
Sometimes "Reload window" helps.

Macbook pro, rvm, ruby 2.5.1, VSCode: Version 1.27.1 (1.27.1)

```sh
which rufo
/Users/eduard/.rvm/gems/ruby-2.5.1@zxc/bin/rufo
```

Install rufo using `rvm do all gem install rufo` and vscode "Reload Window"

rufo works fine in vscode terminal

How can I help to fix?

**Comment by bessey** [comment]
I'm not familiar with rvm (Ruby Version Manager) but it is likely to be an
issue stemming from that. I have not had issues with rbenv.

Perhaps try installing rufo *without* rvm, just using system ruby?

Matt

**Comment by edbond** [comment]
Maybe we can lookup for available rufo in rvm dirs and fallback to just 'rufo'?
I have one in
`/Users/eduard/.rvm/gems/ruby-2.5.1/wrappers/rufo`

**Comment by bessey** [comment]
That sounds like reimplementing PATH to me. The extension simply runs
"rufo", if it's not in PATH, the call will fail. It's your shell's job to
make sure `which rufo` finds something.

Maybe these resources will help
https://rvm.io/rvm/basics#post-install-configuration
https://rvm.io/gemsets/global

Matt
