### ISSUE TITLE
Show syntax error location

### ISSUE THREAD

**Issue by smlparry** [bessey/vscode-rufo#7]
It would be super awesome if this error message actually provided useful information in the form of a stack trace rather than a generic error message, leaving you to hunt down the issue:

![screen shot 2018-04-19 at 3 20 29 pm](https://user-images.githubusercontent.com/7920702/38972655-479e175e-43e5-11e8-9c7d-93c159693bb5.png)

**Comment by cferriss** [comment]
+1

**Comment by bessey** [comment]
The official VS Code Ruby extension has this functionality built in. Enable it like so:

```
  // User Settings or Project Settings
  "ruby.lint": {
    "ruby": true //Runs ruby -wc
  }
```
