### ISSUE TITLE
Will this work for ERB files?

### ISSUE THREAD

**Issue by ecbrodie** [bessey/vscode-rufo#8]
Will vscode-rufo work for editing ERB files?

I have a hunch that it is not. On the latest version of VSCode (1.22.2) and this plugin (0.1.1), no formatter is detected for ERB files. Also, I'm seeing that [only Ruby language is configured in this extension's source code](https://github.com/bessey/vscode-rufo/blob/master/src/extension.ts#L9).

Thank you.

**Comment by bessey** [comment]
Not at present, no. As rufo does not

**Comment by ecbrodie** [comment]
Hmm...alright, thanks
